// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.11.0+v0.31.0
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable




using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
namespace uniffi.spike_ffi;



// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer {
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size) {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            var buffer = _UniFFILib.ffi_spike_ffi_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
            if (buffer.data == IntPtr.Zero) {
                throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
            }
            return buffer;
        });
    }

    public static void Free(RustBuffer buffer) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.ffi_spike_ffi_rustbuffer_free(buffer, ref status);
        });
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len))
            );
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes {
    public int length;
    public IntPtr data;
}


// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType> {
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value) {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        } catch {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf) {
        var stream = rbuf.AsStream();
        try {
           var item = Read(stream);
           if (stream.HasRemaining()) {
               throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
           }
           return item;
        } finally {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType>: FfiConverter<CsType, RustBuffer> {
    public override CsType Lift(RustBuffer value) {
        return LiftFromRustBuffer(value);
    }
    public override RustBuffer Lower(CsType value) {
        return LowerIntoRustBuffer(value);
    }
}


// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus {
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess() {
        return code == 0;
    }

    public bool IsError() {
        return code == 1;
    }

    public bool IsPanic() {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
internal class UniffiException: System.Exception {
    public UniffiException(): base() {}
    public UniffiException(string message): base(message) {}
}

internal class UndeclaredErrorException: UniffiException {
    public UndeclaredErrorException(string message): base(message) {}
}

internal class PanicException: UniffiException {
    public PanicException(string message): base(message) {}
}

internal class AllocationException: UniffiException {
    public AllocationException(string message): base(message) {}
}

internal class InternalException: UniffiException {
    public InternalException(string message): base(message) {}
}

internal class InvalidEnumException: InternalException {
    public InvalidEnumException(string message): base(message) {
    }
}

internal class UniffiContractVersionException: UniffiException {
    public UniffiContractVersionException(string message): base(message) {
    }
}

internal class UniffiContractChecksumException: UniffiException {
    public UniffiContractChecksumException(string message): base(message) {
    }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> where E: System.Exception {
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler: CallStatusErrorHandler<UniffiException> {
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf) {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers {
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E: System.Exception
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess()) {
            return return_value;
        } else if (status.IsError()) {
            throw errorHandler.Lift(status.error_buf);
        } else if (status.IsPanic()) {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0) {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            } else {
                throw new PanicException("Rust panic");
            }
        } else {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E: System.Exception
    {
        _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback) {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }
}

static class FFIObjectUtil {
    public static void DisposeAll(params Object?[] list) {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
   private static void Dispose(Object? obj) {
         if (obj == null) {
             return;
         }

         if (obj is IDisposable disposable) {
             disposable.Dispose();
             return;
         }

         var objType = obj.GetType();
         var typeCode = Type.GetTypeCode(objType);
         if (typeCode != TypeCode.Object) {
             return;
         }

         var genericArguments = objType.GetGenericArguments();
         if (genericArguments.Length == 0 && !objType.IsArray) {
             return;
         }

         if (obj is System.Collections.IDictionary objDictionary) {
             //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
             //for all values as "double" and alike doesn't support interface "IDisposable"
             var valuesType = objType.GetGenericArguments()[1];
             var elementValuesTypeCode = Type.GetTypeCode(valuesType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in objDictionary.Values) {
                 Dispose(value);
             }
         }
         else if (obj is System.Collections.IEnumerable listValues) {
             //This extra code tests to not call "Dispose" for a List<int>()
             //for all keys as "int" and alike doesn't support interface "IDisposable"
             var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
             var elementValuesTypeCode = Type.GetTypeCode(elementType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in listValues) {
                 Dispose(value);
             }
         }
     }
}


// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException: System.Exception {
    public StreamUnderflowException() {
    }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if NET8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToWrite];
 #else
         byte[] buffer = new byte[bytesToWrite];
 #endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4) {
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream) {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length) {
        if (stream.Length - stream.Position < length) {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action){
        foreach (var item in items) {
            action(item);
        }
    }
}

class BigEndianStream {
    Stream stream;
    public BigEndianStream(Stream stream) {
        this.stream = stream;
    }

    public Stream InnerStream => stream;

    public bool HasRemaining() {
        return (stream.Length - Position) > 0;
    }

    public long Position {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer) {
#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);
    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);
    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);
    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);
    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value) {
        unsafe {
            WriteInt(*((int*)&value));
        }
    }
    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length) {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);
    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);
    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);
    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();
    public short ReadShort() => (short)ReadUShort();
    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat() {
        unsafe {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();
    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.


// This is an implementation detail that will be called internally by the public API.
#if NET8_0_OR_GREATER
static partial class _UniFFILib {
#else
static class _UniFFILib {
#endif
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(
        ulong @data,sbyte @pollResult
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureDroppedCallback(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate ulong UniffiCallbackInterfaceClone(
        ulong @handle
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureDroppedCallbackStruct
    {
        public ulong @handle;
        public IntPtr @free;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultF32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultF64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultRustBuffer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultVoid
    {
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultVoid @result
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceChangeListenerMethod0(
        ulong @uniffiHandle,RustBuffer @entityIds,IntPtr @uniffiOutReturn,ref UniffiRustCallStatus _uniffi_out_err
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiVTableCallbackInterfaceChangeListener
    {
        public IntPtr @uniffiFree;
        public IntPtr @uniffiClone;
        public IntPtr @onChange;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    static _UniFFILib() {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
        
        UniffiCallbackInterfaceChangeListener.Register();
        }

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_spike_ffi_fn_clone_changelistener(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_spike_ffi_fn_free_changelistener(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_spike_ffi_fn_init_callback_vtable_changelistener(IntPtr /*_UniFFILib.UniffiVTableCallbackInterfaceChangeListener*/ @vtable
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_spike_ffi_fn_method_changelistener_on_change(ulong @ptr,RustBuffer @entityIds,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_spike_ffi_fn_clone_session(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_spike_ffi_fn_free_session(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_spike_ffi_fn_constructor_session_open(RustBuffer @path,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer uniffi_spike_ffi_fn_method_session_list(ulong @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     uint uniffi_spike_ffi_fn_method_session_listener_failures(ulong @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_spike_ffi_fn_method_session_panic_now(ulong @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer uniffi_spike_ffi_fn_method_session_render(ulong @ptr,uint @size,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_spike_ffi_fn_method_session_save(ulong @ptr,RustBuffer @item,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_spike_ffi_fn_method_session_set_listener(ulong @ptr,ulong @listener,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_spike_ffi_fn_method_session_start_ticker(ulong @ptr,uint @count,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer ffi_spike_ffi_rustbuffer_alloc(ulong @size,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer ffi_spike_ffi_rustbuffer_from_bytes(ForeignBytes @bytes,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rustbuffer_free(RustBuffer @buf,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer ffi_spike_ffi_rustbuffer_reserve(RustBuffer @buf,ulong @additional,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_u8(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_u8(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_u8(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     byte ffi_spike_ffi_rust_future_complete_u8(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_i8(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_i8(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_i8(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     sbyte ffi_spike_ffi_rust_future_complete_i8(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_u16(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_u16(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_u16(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort ffi_spike_ffi_rust_future_complete_u16(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_i16(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_i16(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_i16(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     short ffi_spike_ffi_rust_future_complete_i16(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_u32(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_u32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_u32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     uint ffi_spike_ffi_rust_future_complete_u32(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_i32(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_i32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_i32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     int ffi_spike_ffi_rust_future_complete_i32(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_u64(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_u64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_u64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong ffi_spike_ffi_rust_future_complete_u64(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_i64(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_i64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_i64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     long ffi_spike_ffi_rust_future_complete_i64(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_f32(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_f32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_f32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     float ffi_spike_ffi_rust_future_complete_f32(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_f64(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_f64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_f64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     double ffi_spike_ffi_rust_future_complete_f64(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_rust_buffer(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_rust_buffer(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_rust_buffer(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer ffi_spike_ffi_rust_future_complete_rust_buffer(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_poll_void(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_cancel_void(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_free_void(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_spike_ffi_rust_future_complete_void(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_spike_ffi_checksum_method_changelistener_on_change(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_spike_ffi_checksum_method_session_list(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_spike_ffi_checksum_method_session_listener_failures(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_spike_ffi_checksum_method_session_panic_now(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_spike_ffi_checksum_method_session_render(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_spike_ffi_checksum_method_session_save(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_spike_ffi_checksum_method_session_set_listener(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_spike_ffi_checksum_method_session_start_ticker(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_spike_ffi_checksum_constructor_session_open(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("spike_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("spike_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     uint ffi_spike_ffi_uniffi_contract_version(
    );

    

    static void uniffiCheckContractApiVersion() {
        var scaffolding_contract_version = _UniFFILib.ffi_spike_ffi_uniffi_contract_version();
        if (30 != scaffolding_contract_version) {
            throw new UniffiContractVersionException($"uniffi.spike_ffi: uniffi bindings expected version `30`, library returned `{scaffolding_contract_version}`");
        }
    }
    static void uniffiCheckApiChecksums() {
        {
            var checksum = _UniFFILib.uniffi_spike_ffi_checksum_method_changelistener_on_change();
            if (checksum != 21114) {
                throw new UniffiContractChecksumException($"uniffi.spike_ffi: uniffi bindings expected function `uniffi_spike_ffi_checksum_method_changelistener_on_change` checksum `21114`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_spike_ffi_checksum_method_session_list();
            if (checksum != 9467) {
                throw new UniffiContractChecksumException($"uniffi.spike_ffi: uniffi bindings expected function `uniffi_spike_ffi_checksum_method_session_list` checksum `9467`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_spike_ffi_checksum_method_session_listener_failures();
            if (checksum != 42302) {
                throw new UniffiContractChecksumException($"uniffi.spike_ffi: uniffi bindings expected function `uniffi_spike_ffi_checksum_method_session_listener_failures` checksum `42302`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_spike_ffi_checksum_method_session_panic_now();
            if (checksum != 51191) {
                throw new UniffiContractChecksumException($"uniffi.spike_ffi: uniffi bindings expected function `uniffi_spike_ffi_checksum_method_session_panic_now` checksum `51191`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_spike_ffi_checksum_method_session_render();
            if (checksum != 46772) {
                throw new UniffiContractChecksumException($"uniffi.spike_ffi: uniffi bindings expected function `uniffi_spike_ffi_checksum_method_session_render` checksum `46772`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_spike_ffi_checksum_method_session_save();
            if (checksum != 1740) {
                throw new UniffiContractChecksumException($"uniffi.spike_ffi: uniffi bindings expected function `uniffi_spike_ffi_checksum_method_session_save` checksum `1740`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_spike_ffi_checksum_method_session_set_listener();
            if (checksum != 40902) {
                throw new UniffiContractChecksumException($"uniffi.spike_ffi: uniffi bindings expected function `uniffi_spike_ffi_checksum_method_session_set_listener` checksum `40902`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_spike_ffi_checksum_method_session_start_ticker();
            if (checksum != 30300) {
                throw new UniffiContractChecksumException($"uniffi.spike_ffi: uniffi bindings expected function `uniffi_spike_ffi_checksum_method_session_start_ticker` checksum `30300`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_spike_ffi_checksum_constructor_session_open();
            if (checksum != 4722) {
                throw new UniffiContractChecksumException($"uniffi.spike_ffi: uniffi bindings expected function `uniffi_spike_ffi_checksum_constructor_session_open` checksum `4722`, library returned `{checksum}`");
            }
        }
    }
}

// Public interface members begin here.

#pragma warning disable 8625




class FfiConverterUInt32: FfiConverter<uint, uint> {
    public static FfiConverterUInt32 INSTANCE = new FfiConverterUInt32();

    public override uint Lift(uint value) {
        return value;
    }

    public override uint Read(BigEndianStream stream) {
        return stream.ReadUInt();
    }

    public override uint Lower(uint value) {
        return value;
    }

    public override int AllocationSize(uint value) {
        return 4;
    }

    public override void Write(uint value, BigEndianStream stream) {
        stream.WriteUInt(value);
    }
}



class FfiConverterDouble: FfiConverter<double, double> {
    public static FfiConverterDouble INSTANCE = new FfiConverterDouble();

    public override double Lift(double value) {
        return value;
    }

    public override double Read(BigEndianStream stream) {
        return stream.ReadDouble();
    }

    public override double Lower(double value) {
        return value;
    }

    public override int AllocationSize(double value) {
        return 8;
    }

    public override void Write(double value, BigEndianStream stream) {
        stream.WriteDouble(value);
    }
}



class FfiConverterString: FfiConverter<string, RustBuffer> {
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value) {
        try {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        } finally {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value) {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}




class FfiConverterByteArray: FfiConverterRustBuffer<byte[]> {
    public static FfiConverterByteArray INSTANCE = new FfiConverterByteArray();

    public override byte[] Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        return stream.ReadBytes(length);
    }

    public override int AllocationSize(byte[] value) {
        return 4 + value.Length;
    }

    public override void Write(byte[] value, BigEndianStream stream) {
        stream.WriteInt(value.Length);
        stream.WriteBytes(value);
    }
}



internal interface ChangeListener {
    /// <exception cref="ListenerException"></exception>
    void OnChange(string[] @entityIds);
}
internal class ChangeListenerImpl : ChangeListener, IDisposable {
    protected ulong pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public ChangeListenerImpl(ulong pointer) {
        this.pointer = pointer;
    }

    ~ChangeListenerImpl() {
        Destroy();
    }

    protected void FreeRustArcPtr() {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.uniffi_spike_ffi_fn_free_changelistener(this.pointer, ref status);
        });
    }

    protected ulong CloneRustArcPtr() {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            return _UniFFILib.uniffi_spike_ffi_fn_clone_changelistener(this.pointer, ref status);
        });
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter() 
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L) throw new System.ObjectDisposedException(String.Format("'{0}' object has already been destroyed", this.GetType().Name));
            if (count == long.MaxValue) throw new System.OverflowException(String.Format("'{0}' call counter would overflow", this.GetType().Name));

        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter() 
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0) {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<ulong> action)
    {
        IncrementCallCounter();
        try {
            action(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<ulong, T> func)
    {   
        IncrementCallCounter();
        try {
            return func(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    
    /// <exception cref="ListenerException"></exception>
    public void OnChange(string[] @entityIds) {
        CallWithPointer(thisPtr =>
    _UniffiHelpers.RustCallWithError(FfiConverterTypeListenerError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_spike_ffi_fn_method_changelistener_on_change(thisPtr, FfiConverterSequenceString.INSTANCE.Lower(@entityIds), ref _status)
));
    }
    
    
    

    
}
class UniffiCallbackInterfaceChangeListener {
    static void OnChange(ulong @uniffiHandle,RustBuffer @entityIds,IntPtr @uniffiOutReturn,ref UniffiRustCallStatus _uniffi_out_err) {
        var handle = @uniffiHandle;
        try {
            if (!FfiConverterTypeChangeListener.INSTANCE.handleMap.TryGet(handle, out var uniffiObject)) {
                throw new InternalException($"No callback in handlemap '{handle}'");
            }
            uniffiObject.OnChange(
                FfiConverterSequenceString.INSTANCE.Lift(@entityIds));

            _uniffi_out_err.code = UniffiCallbackResponseStatus.SUCCESS;
        }
        catch (ListenerException e) {
            try {
                _uniffi_out_err.code = UniffiCallbackResponseStatus.ERROR;
                _uniffi_out_err.error_buf = FfiConverterTypeListenerError.INSTANCE.Lower(e);
            } catch {
                _uniffi_out_err.code = UniffiCallbackResponseStatus.UNEXPECTED_ERROR;
            }
        }
        catch (System.Exception e){
            _uniffi_out_err.code = UniffiCallbackResponseStatus.UNEXPECTED_ERROR;
            try {
                _uniffi_out_err.error_buf = FfiConverterString.INSTANCE.Lower(e.Message);
            }
            catch {
            }
        }
    }

    static void UniffiFree(ulong @handle) {
        FfiConverterTypeChangeListener.INSTANCE.handleMap.Remove(@handle);
    }

    static ulong UniffiClone(ulong @handle) {
        try {
            if (!FfiConverterTypeChangeListener.INSTANCE.handleMap.TryGet(@handle, out var obj)) {
                throw new InternalException($"No callback in handlemap '{@handle}'");
            }
            return FfiConverterTypeChangeListener.INSTANCE.handleMap.Insert(obj);
        } catch (System.Exception) {
            return 0; // 0 is never a valid handle; ConcurrentHandleMap starts at 1
        }
    }
    static _UniFFILib.UniffiCallbackInterfaceChangeListenerMethod0 _m0 = new _UniFFILib.UniffiCallbackInterfaceChangeListenerMethod0(OnChange);
    static _UniFFILib.UniffiCallbackInterfaceFree _callback_interface_free = new _UniFFILib.UniffiCallbackInterfaceFree(UniffiFree);
    static _UniFFILib.UniffiCallbackInterfaceClone _callback_interface_clone = new _UniFFILib.UniffiCallbackInterfaceClone(UniffiClone);

    private static GCHandle? _vtablePin;

    public static void Register() {
        if (_vtablePin.HasValue) return;
        _UniFFILib.UniffiVTableCallbackInterfaceChangeListener _vtable = new _UniFFILib.UniffiVTableCallbackInterfaceChangeListener {
            @onChange = Marshal.GetFunctionPointerForDelegate(_m0),
            @uniffiFree = Marshal.GetFunctionPointerForDelegate(_callback_interface_free),
            @uniffiClone = Marshal.GetFunctionPointerForDelegate(_callback_interface_clone),
        };

        // Pin the vtable so the GC never moves it. The GCHandle is intentionally never freed —
        // this pin must remain valid for the process lifetime.
        _vtablePin = GCHandle.Alloc(_vtable, GCHandleType.Pinned);
        _UniFFILib.uniffi_spike_ffi_fn_init_callback_vtable_changelistener(_vtablePin.Value.AddrOfPinnedObject());
    }
}



class ConcurrentHandleMap<T> where T: notnull {
    readonly ConcurrentDictionary<ulong, T> _map = new();

    // Handles are odd numbers (1, 3, 5, ...) — the lowest bit must always be set.
    // Rust uses (handle & 1) to distinguish foreign-language handles from Rust Arc
    // pointers, which are always even due to memory alignment. See uniffi_core/src/ffi/handle.rs.
    const long HANDLE_INITIAL = 1;
    const long HANDLE_DELTA = 2;
    long _currentHandle = HANDLE_INITIAL - HANDLE_DELTA;

    public ulong Insert(T obj) {
        var handle = (ulong)Interlocked.Add(ref _currentHandle, HANDLE_DELTA);
        if (!_map.TryAdd(handle, obj)) {
            throw new InternalException("ConcurrentHandleMap: Duplicate handle");
        }
        return handle;
    }

    public bool TryGet(ulong handle, [NotNullWhen(true)] out T? result) {
        return _map.TryGetValue(handle, out result);
    }

    public T Get(ulong handle) {
        if (_map.TryGetValue(handle, out var result)) {
            return result;
        } else {
            throw new InternalException("ConcurrentHandleMap: Invalid handle");
        }
    }

    public bool Remove(ulong handle) {
        return _map.TryRemove(handle, out _);
    }

    public bool Remove(ulong handle, [NotNullWhen(true)] out T? result) {
        return _map.TryRemove(handle, out result);
    }
}
static class UniffiCallbackResponseStatus {
    public static sbyte SUCCESS = 0;
    public static sbyte ERROR = 1;
    public static sbyte UNEXPECTED_ERROR = 2;
}

class FfiConverterTypeChangeListener: FfiConverter<ChangeListener, ulong> {
    public ConcurrentHandleMap<ChangeListener> handleMap = new ConcurrentHandleMap<ChangeListener>();
    
    public static FfiConverterTypeChangeListener INSTANCE = new FfiConverterTypeChangeListener();

    static FfiConverterTypeChangeListener() {
        UniffiCallbackInterfaceChangeListener.Register();
    }

    public override ulong Lower(ChangeListener value) {
        if (value is ChangeListenerImpl rustObj) {
            // Rust-implemented object. Clone the handle and return it.
            return rustObj.CallWithPointer(thisPtr => thisPtr);
        } else {
            // C# object, generate a new handle map entry and return it.
            return handleMap.Insert(value);
        }
    }

    public override ChangeListener Lift(ulong value) {
        if ((value & 1UL) == 0UL) {
            // Rust-generated handle, construct a new wrapper.
            return new ChangeListenerImpl(value);
        } else {
            // C#-generated handle, retrieve and remove from the handle map.
            if (handleMap.Remove(value, out var obj)) {
                return obj;
            } else {
                throw new InternalException($"No callback in handlemap '{value}'");
            }
        }
    }

    public override ChangeListener Read(BigEndianStream stream) {
        return Lift(stream.ReadULong());
    }

    public override int AllocationSize(ChangeListener value) {
        return 8;
    }

    public override void Write(ChangeListener value, BigEndianStream stream) {
        stream.WriteULong(Lower(value));
    }
}



internal interface ISession {
    Item[] List();
    uint ListenerFailures();
    void PanicNow();
    byte[] Render(uint @size);
    /// <exception cref="SpikeException"></exception>
    void Save(Item @item);
    void SetListener(ChangeListener @listener);
    void StartTicker(uint @count);
}
internal class Session : ISession, IDisposable {
    protected ulong pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public Session(ulong pointer) {
        this.pointer = pointer;
    }

    ~Session() {
        Destroy();
    }

    protected void FreeRustArcPtr() {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.uniffi_spike_ffi_fn_free_session(this.pointer, ref status);
        });
    }

    protected ulong CloneRustArcPtr() {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            return _UniFFILib.uniffi_spike_ffi_fn_clone_session(this.pointer, ref status);
        });
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter() 
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L) throw new System.ObjectDisposedException(String.Format("'{0}' object has already been destroyed", this.GetType().Name));
            if (count == long.MaxValue) throw new System.OverflowException(String.Format("'{0}' call counter would overflow", this.GetType().Name));

        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter() 
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0) {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<ulong> action)
    {
        IncrementCallCounter();
        try {
            action(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<ulong, T> func)
    {   
        IncrementCallCounter();
        try {
            return func(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    
    public Item[] List() {
        return CallWithPointer(thisPtr => FfiConverterSequenceTypeItem.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_spike_ffi_fn_method_session_list(thisPtr,  ref _status)
)));
    }
    
    
    public uint ListenerFailures() {
        return CallWithPointer(thisPtr => FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_spike_ffi_fn_method_session_listener_failures(thisPtr,  ref _status)
)));
    }
    
    
    public void PanicNow() {
        CallWithPointer(thisPtr =>
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_spike_ffi_fn_method_session_panic_now(thisPtr,  ref _status)
));
    }
    
    
    
    public byte[] Render(uint @size) {
        return CallWithPointer(thisPtr => FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_spike_ffi_fn_method_session_render(thisPtr, FfiConverterUInt32.INSTANCE.Lower(@size), ref _status)
)));
    }
    
    
    /// <exception cref="SpikeException"></exception>
    public void Save(Item @item) {
        CallWithPointer(thisPtr =>
    _UniffiHelpers.RustCallWithError(FfiConverterTypeSpikeError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_spike_ffi_fn_method_session_save(thisPtr, FfiConverterTypeItem.INSTANCE.Lower(@item), ref _status)
));
    }
    
    
    
    public void SetListener(ChangeListener @listener) {
        CallWithPointer(thisPtr =>
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_spike_ffi_fn_method_session_set_listener(thisPtr, FfiConverterTypeChangeListener.INSTANCE.Lower(@listener), ref _status)
));
    }
    
    
    
    public void StartTicker(uint @count) {
        CallWithPointer(thisPtr =>
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_spike_ffi_fn_method_session_start_ticker(thisPtr, FfiConverterUInt32.INSTANCE.Lower(@count), ref _status)
));
    }
    
    
    

    
    /// <exception cref="SpikeException"></exception>
    public static Session Open(string @path) {
        return new Session(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeSpikeError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_spike_ffi_fn_constructor_session_open(FfiConverterString.INSTANCE.Lower(@path), ref _status)
));
    }
    
    
}
class FfiConverterTypeSession: FfiConverter<Session, ulong> {
    public static FfiConverterTypeSession INSTANCE = new FfiConverterTypeSession();


    public override ulong Lower(Session value) {
        return value.CallWithPointer(thisPtr => thisPtr);
    }

    public override Session Lift(ulong value) {
        return new Session(value);
    }

    public override Session Read(BigEndianStream stream) {
        return Lift(stream.ReadULong());
    }

    public override int AllocationSize(Session value) {
        return 8;
    }

    public override void Write(Session value, BigEndianStream stream) {
        stream.WriteULong(Lower(value));
    }
}



internal record Item (
    string Id, 
    string Name, 
    double Concentration, 
    string[] Tags
) {
}

class FfiConverterTypeItem: FfiConverterRustBuffer<Item> {
    public static FfiConverterTypeItem INSTANCE = new FfiConverterTypeItem();

    public override Item Read(BigEndianStream stream) {
        return new Item(
            Id: FfiConverterString.INSTANCE.Read(stream),
            Name: FfiConverterString.INSTANCE.Read(stream),
            Concentration: FfiConverterDouble.INSTANCE.Read(stream),
            Tags: FfiConverterSequenceString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(Item value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.Id)
            + FfiConverterString.INSTANCE.AllocationSize(value.Name)
            + FfiConverterDouble.INSTANCE.AllocationSize(value.Concentration)
            + FfiConverterSequenceString.INSTANCE.AllocationSize(value.Tags);
    }

    public override void Write(Item value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.Id, stream);
            FfiConverterString.INSTANCE.Write(value.Name, stream);
            FfiConverterDouble.INSTANCE.Write(value.Concentration, stream);
            FfiConverterSequenceString.INSTANCE.Write(value.Tags, stream);
    }
}





internal class ListenerException: UniffiException {
    ListenerException() : base() {}
    ListenerException(String @Message) : base(@Message) {}

    // Each variant is a nested class
    
    
    public class Failed : ListenerException {
        // Members
        public string @message;

        // Constructor
        public Failed(
                string @message) : base(
                "@message" + "=" + @message) {

            this.@message = @message;
        }
    }
    

    
}

class FfiConverterTypeListenerError : FfiConverterRustBuffer<ListenerException>, CallStatusErrorHandler<ListenerException> {
    public static FfiConverterTypeListenerError INSTANCE = new FfiConverterTypeListenerError();

    public override ListenerException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1:
                return new ListenerException.Failed(
                    FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeListenerError.Read()", value));
        }
    }

    public override int AllocationSize(ListenerException value) {
        switch (value) {

            case ListenerException.Failed variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@message);
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeListenerError.AllocationSize()", value));
        }
    }

    public override void Write(ListenerException value, BigEndianStream stream) {
        switch (value) {
            case ListenerException.Failed variant_value:
                stream.WriteInt(1);
                FfiConverterString.INSTANCE.Write(variant_value.@message, stream);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeListenerError.Write()", value));
        }
    }
}





internal class SpikeException: UniffiException {
    SpikeException() : base() {}
    SpikeException(String @Message) : base(@Message) {}

    // Each variant is a nested class
    
    
    public class CheckedOut : SpikeException {
        // Members
        public string @user;
        public string @machine;

        // Constructor
        public CheckedOut(
                string @user, 
                string @machine) : base(
                "@user" + "=" + @user+ ", " +
                "@machine" + "=" + @machine) {

            this.@user = @user;

            this.@machine = @machine;
        }
    }
    
    
    public class Io : SpikeException {
        // Members
        public string @message;

        // Constructor
        public Io(
                string @message) : base(
                "@message" + "=" + @message) {

            this.@message = @message;
        }
    }
    

    
}

class FfiConverterTypeSpikeError : FfiConverterRustBuffer<SpikeException>, CallStatusErrorHandler<SpikeException> {
    public static FfiConverterTypeSpikeError INSTANCE = new FfiConverterTypeSpikeError();

    public override SpikeException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1:
                return new SpikeException.CheckedOut(
                    FfiConverterString.INSTANCE.Read(stream),
                    FfiConverterString.INSTANCE.Read(stream));
            case 2:
                return new SpikeException.Io(
                    FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeSpikeError.Read()", value));
        }
    }

    public override int AllocationSize(SpikeException value) {
        switch (value) {

            case SpikeException.CheckedOut variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@user)
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@machine);

            case SpikeException.Io variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@message);
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeSpikeError.AllocationSize()", value));
        }
    }

    public override void Write(SpikeException value, BigEndianStream stream) {
        switch (value) {
            case SpikeException.CheckedOut variant_value:
                stream.WriteInt(1);
                FfiConverterString.INSTANCE.Write(variant_value.@user, stream);
                FfiConverterString.INSTANCE.Write(variant_value.@machine, stream);
                break;
            case SpikeException.Io variant_value:
                stream.WriteInt(2);
                FfiConverterString.INSTANCE.Write(variant_value.@message, stream);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeSpikeError.Write()", value));
        }
    }
}




class FfiConverterSequenceString: FfiConverterRustBuffer<string[]> {
    public static FfiConverterSequenceString INSTANCE = new FfiConverterSequenceString();

    public override string[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new string[length];
        var readFn = FfiConverterString.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(string[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(string[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterString.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}




class FfiConverterSequenceTypeItem: FfiConverterRustBuffer<Item[]> {
    public static FfiConverterSequenceTypeItem INSTANCE = new FfiConverterSequenceTypeItem();

    public override Item[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new Item[length];
        var readFn = FfiConverterTypeItem.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(Item[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterTypeItem.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(Item[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterTypeItem.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}
#pragma warning restore 8625
internal static class SpikeFfiMethods {
}

